### ISSUE TITLE
Some questions about model hyperparameter

### ISSUE THREAD

**Issue by PengShi27** [xuuuluuu/SynLSTM-for-NER#1]
Hi, Thank you for sharing your code. The default value of num_lstm_layer in the code is 0. It feels a little unreasonable to set the value of num_lstm_layer  to 0. I don't know how much you set the value of num_lstm_layer  in the experiment. I get an error when I set the value of num_lstm_layer   to 1.
![image](https://user-images.githubusercontent.com/30725927/118423349-67d32400-b6f7-11eb-8df1-84685551898f.png)
![image](https://user-images.githubusercontent.com/30725927/118423420-8fc28780-b6f7-11eb-9a28-abec4ed7e62f.png)

**Comment by xuuuluuu** [comment]
Hi, thanks for the question. Our code is designed to run all the baselines and our model at the same time.

When setting "num_lstm_layer", which means you are also running with the standard LSTM. The error is because you set the model to use both Bi-LSTM and Syn-LSTM at the same time.

I suggest using the default configs, which is exactly our proposed structure. If you want to further test other customized model structures, you may need to make sure your structure is reasonable.

**Comment by PengShi27** [comment]
Does this mean that Syn-LSTM is used when num_lstm_layer is set to 0?

**Comment by xuuuluuu** [comment]
That is right. Note that the flag --dep_model=dggcn (by default) is where we call both GCN and our Syn-LSTM model. The flag --num_lstm-layer is designed for running some standard LSTM baselines, and should be set to 0 (by default) when running our model.

**Comment by PengShi27** [comment]
Thanks for your reply!
